* Setup
  Currently I use emacs on Linux (Ubuntu) primarily. But at some point
  I have used emacs on Linux (ubuntu), MacOS as well as Windows. So
  this setup has different section for specific OS where applicable.

** Download Emacs
*** Ubuntu 24.04
    Install emacs from source. Detailed steps in my org-roam notes
    (closed-sourced). Also note that to compile emacs 30 from source,
    treesitter-lib needs to be compiled from version v0.24.0. Don't
    use what's available in ubuntu's apt packages
*** MacOS
    On MacOS I install emacs using the [[https://github.com/d12frosted/homebrew-emacs-plus][homebrew-emacs-plus]] formula. To
    install follow the instructions in the README of the above git
    repo. For quick reference, you just need to run,
    #+begin_src bash
      brew tap d12frosted/emacs-plus
      brew install emacs-plug@29

      # Create a link in Applications folder
      osascript -e 'tell application "Finder" to make alias file to posix file "/usr/local/opt/emacs-plus@29/Emacs.app" at POSIX file "/Applications"'
    #+end_src
*** TODO Windows

** System dependencies
   This emacs setup depends on external tools and programs, so they
   need to be installed and ensured to be available in the ~PATH~ that
   emacs is started with

*** Configuring PATH
**** Ubuntu
     GNOME uses PATH variable from the systemd environment. To modify
     the PATH, create a conf file at
     =~/.config/environment.d/path.conf= as follows,
     #+begin_src bash
       # Dirs to be added to PATH in the env of apps launched from GUI

       PATH=$HOME/.local/bin:$HOME/.nvm/versions/node/v22.12.0/bin:$PATH
     #+end_src
     Then restart the machine. Or re-import environment to avoid restart
     #+begin_src bash
       systemctl --user import-environment PATH
     #+end_src
     Verify that the PATH was picked up by systemd environment
     #+begin_src bash
       systemctl --user show-environment | grep PATH
     #+end_src
**** TODO MacOS
**** TODO Windows

** Programming environments
*** Python
**** Install Python
***** MacOS
     Even though python is installed using xcode command line tools, it
     has complications. So we will first install python again using
     ~homebrew~
     #+begin_src bash
       brew install python
     #+end_src
     This would install python3 executable in the ~/usr/local/bin~
     directory.
****** Ensure that python executable is available on the machine
       On later MacOS versions, ~python~ is not available as it was
       meant for python2 which is deprecated. However, many emacs modes
       assume ~python~ executable to be available. In that case, create
       a symlink to it
       #+begin_src bash
         bin_dir=$(dirname $(which python3))
         sudo ln -sv $bin_dir/python3 $bin_dir/python
       #+end_src
****** TODO Move to uv based installation on MacOS
***** Ubuntu
      ~uv~ is a much better way to work with Python. It's all you need!
***** TODO Windows
****** TODO Move to uv based installation on Windows

*** Rust
    Follow the rust documentation to install rust on the machine.

    The only external dependency for rust development is
    [[https://rust-analyzer.github.io/][rust-analyzer]]. It can be installed using homebrew
    #+begin_src bash
      rustup component add rust-analyzer
    #+end_src

    For rust development, we're using 3 emacs modes:

    1. ~rust-mode~: Provides indentation, syntax highlighting and
       integration with cargo, rustfmt (formatter) and clippy (lint)
    2. ~rustic~ mode: Builds on top of the rust-mode and provides
       missing features. One of the thing that ~rustic~ does is
       configure eglot but I have disabed that and doing it separately
       instead for more control. So at this point, I am not sure what
       exactly is ~rustic~ being used for.
    3. ~cargo~: To perform cargo tasks from emacs
    4. ~rust-playground~ mode: Minor mode for quickly running snippets
       of code from within emacs as an alternative to the online rust
       playground - https://play.rust-lang.org

**** Known issues
     - Rustfmt indentation not consistent with emacs indentation
       + https://github.com/rust-lang/rustfmt/issues/3157

*** SQL
    - Install pgformatter for formatting sql buffers
      #+begin_src bash
        brew install pgformatter
      #+end_src

*** C langs i.e. C, C++
**** Install the clangd language server
     #+begin_src bash
       brew install llvm
     #+end_src

*** Javascript/Typescript
**** Install node and npm
**** Install the typescript and typescript-language-server
     #+begin_src bash
       npm install -g typescript-language-server typescript
     #+end_src
*** Clojure
**** Leiningen
**** nREPL middleware
     - https://github.com/clojure-emacs/cider-nrepl
     - Required by the latest Cider release
     - The easiest way to set it up is to add it as a leiningen plugin
       either in your project's ~project.clj~ file or in the ~:user~
       profile in ~~/.lein/profiles.clj~.
     - https://github.com/clojure-emacs/cider#cider-nrepl-middleware
**** clj-kondo
     - https://github.com/clj-kondo/clj-kondo
     - For flycheck in clojure buffers

** Org mode
*** Custom script for lower case UUIDs on MacOS
    On macos, the default ~uuidgen~ script generates UUIDs in
    uppercase. For consistency, enforce lower case UUID generation by
    copying the ~uuidgen-lower~ provided in this repo
    #+begin_src bash
      ln -sv bin/uuidgen-lower /usr/local/bin/
    #+end_src

*** Graphviz for visualizing org roam graph
    Graphviz can be handy for visualizing org-roam graph although
    org-roam-ui is a much better interface.
    #+begin_src bash
      brew install graphviz
    #+end_src
    Note that graphviz is not required for org-roam-ui

*** org-ledger
    Ledger needs to be installed
    #+begin_src bash
      brew install ledger
    #+end_src

** Projectile
*** [[https://github.com/BurntSushi/ripgrep][Ripgrep]] is required for search functionality in projectile mode
*** Cygwin on Windows
    On windows, cygwin needs to be installed
    #+begin_src ps1
      choco install Cygwin
    #+end_src

** Controlling in-browser youtube video player from emacs
   - Often I use emacs for taking notes while watching a youtube video
     side-by-side (by splitting the screen). It's handy to be able to
     control the youtube video from inside emacs.
   - This only works on linux as it uses d-bus as the messaging layer
     between processes
   - Pre-requisites
     1. [[https://github.com/lt-mayonesa/browser-mpris2][browser-mpris2]] native component and firefox
        extension. Follow instructions from github README
     2. playerctl
        #+begin_src bash
          sudo apt install playerctl
        #+end_src

